Vet Clinic: - Feature/update table
microvese-projects/vet-clinic pull request #2
Opened 2023-06-13 16:00 UTC by Bennyjoez

## Vet Clinic: - Feature/update table 🪶 

I have managed to effect the following changes in my database: ♻️ 👨🏾‍💻 
 - I have added an extra column to the animals' table. ➕ 
 - I have Added species for different animals. ➕ 
 - I have queried the number of animals. ➕ 
 - I have worked with transactions in the database. ➕ 
 - I have queried the data with GROUP BY clauses and ORDER BY clauses. ➕ 
 - I have taken screenshots of the results. ➕ 
![Screenshot from 2023-06-13 17-15-21](https://github.com/microvese-projects/vet-clinic/assets/108814163/ac457697-d894-4310-b891-298bdc66f8dd)
![Screenshot from 2023-06-13 17-20-31](https://github.com/microvese-projects/vet-clinic/assets/108814163/85a7e195-2a0d-4b24-ad51-71114ce584c6)
![Screenshot from 2023-06-13 17-35-35](https://github.com/microvese-projects/vet-clinic/assets/108814163/464d29e1-6133-4d89-bcc4-22a47c1064f8)
![Screenshot from 2023-06-13 17-35-42](https://github.com/microvese-projects/vet-clinic/assets/108814163/214a62e8-be69-4170-bc02-866b9d380968)
![Screenshot from 2023-06-13 18-36-44](https://github.com/microvese-projects/vet-clinic/assets/108814163/0925b6e3-37c7-4743-b4ec-284b8acc1947)

2023-06-13 16:18 UTC, mukhammadrizooff requested changes
Hi @Bennyjoez, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 16:18 UTC, mukhammadrizooff commented on data.sql
> +  ('Ditto', '2022-05-14', 4, true, 22);
- [ ] [REQUIRED] Good job so far! Please give correct `data` to your `VALUES` =>

- `[YOURS WRONG VALUES]`
```sql
INSERT INTO animals 
  (date_of_birth, weight_kg)
VALUES
  ('2020-08-02', 11),
  ('2021-11-15', 5.7),
  ('1993-04-02', 12.13),
  ('2005-06-12', 45),
  ('1998-08-13', 17),
```

- `[CORRECT VALUES]`
```sql
    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Charmander', '2020/2/8', '0', 'false', '-11.0');

    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Plantmon', '2021/11/15', '2', 'true', '-5.7');

    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Squirtle', '1993/04/02', '3', 'false', '-12.13');

    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Angemon', '2005/06/12', '1', 'true', '-45.0');

    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Blossom', '1998/10/13', '3', 'true', '17.0');
```

2023-06-14 03:02 UTC, Bennyjoez commented on data.sql
> +  ('Ditto', '2022-05-14', 4, true, 22);
Hello @mukhammadrizooff. 
Thank you for pointing the issue out. I was able to identify it and write a script to fix the data. 📜  Issue solved 🟢  
![Screenshot from 2023-06-14 05-59-55](https://github.com/microvese-projects/vet-clinic/assets/108814163/5d2a19fe-8a0e-4226-a235-a68e9bc8018a)

2023-06-14 03:11 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Bennyjoez,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-14 03:11 UTC, Omar-Muhamad commented on data.sql
> +COMMIT;
- [ ] As required by the previous reviewer, you suppose to correct the entered data values, not make a transaction to correct them, Please fix that.

2023-06-14 04:06 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @Bennyjoez,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-14 04:12 UTC, Bennyjoez commented
Thank you very much, gentlemen. 👍🏾  @mukhammadrizooff  @Omar-Muhamad

2023-06-14 04:13 UTC, merged